import os
import numpy as np
from matplotlib import pyplot as plt
from metrics_per_channel import load_image_ycbcr

def _save_histograms(orig_path, output_dir, y_limits = None, orig = True):
    """Generates synchronized histograms for Original and Compressed images."""
    os.makedirs(output_dir, exist_ok=True)
    
    # Load images exactly how the evaluation script does (YCbCr space)
    orig_ycbcr = load_image_ycbcr(orig_path)
    
    channels = ["Y", "Cb", "Cr"]
    channel_names = ["Y (Luminosity)", "Cb (Blue-Difference)", "Cr (Red-Difference)"]
    
    plt.style.use('dark_background')
    calculated_limits = {}
    
    for i in range(3):
        orig_ch = orig_ycbcr[:, :, i]
        
        # Determine the Y-axis limit
        if y_limits is None:
            # Calculate from the current image
            counts, _ = np.histogram(orig_ch.ravel(), bins=256, range=[0, 255])
            y_limit = counts.max() * 2
            calculated_limits[channels[i]] = y_limit
        else:
            # Use the exact limit passed from the original image
            y_limit = y_limits[channels[i]]
        
        # 2. Save Histogram
        fig_orig = plt.figure()
        plt.hist(orig_ch.ravel(), bins=256, range=[0, 255])
        plt.title(f"{'Original' if orig else 'Compressed'} {channel_names[i]} Histogram")
        plt.xlabel("Pixel Intensity (0-255)")
        plt.ylabel("Pixel Count")
        plt.xlim([0, 255])
        plt.ylim([0, y_limit])
        plt.ticklabel_format(style='plain', axis='y')
        plt.savefig(os.path.join(output_dir, f"Hist_{'Orig' if orig else 'Comp'}_{channels[i]}.png"), bbox_inches='tight', dpi=200)
        plt.close(fig_orig)
        
    return calculated_limits if y_limits is None else None
    
    
# --- Pipeline Wrapper Functions ---

def save_original_histogram(orig_path, output_dir):
    """
    To be run in Phase 1 (Pre-processing).
    Returns a dictionary of limits: e.g., {'Y': 1200, 'Cb': 500, 'Cr': 450}
    """
    return _save_histograms(orig_path, output_dir, orig = True, y_limits=None)

def save_compressed_histogram(comp_path, output_dir, y_limits):
    """
    To be run in Phase 2 (Parallel Workers).
    Requires the y_limits dictionary generated by the original image.
    """
    _save_histograms(comp_path, output_dir, orig = False, y_limits=y_limits)